///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class ImagesResource {
  ImagesResource._();

  static const String launcherIcon =
      'assets/app_icons/launcher_icon/launcher_icon.png';
  static const String pdf = 'assets/icons/pdf.svg';
  static const String signIn = 'assets/icons/sign_in.svg';
  static const String signUp = 'assets/icons/sign_up.svg';
  static const String splashIcon =
      'assets/app_icons/splash_icon/splash_icon.png';
}
